---
title: Startup Sonoma County
#email: startupsonomaco@example.com
description: >-
  Startup Sonoma County provides a productive and dynamic environment to help
  Sonoma county technology startups and entrepreneurs grow and succeed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://startupsonoma.com"
twitter_username: startupsonomaco
github_username:  startupsonoma
google_analytics: 'UA-118274675-1'

header_pages:
  - slack.md
  - sponsor.md
  - conduct.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
